### ISSUE TITLE
无法正常使用？

### ISSUE THREAD

**Issue by purofle** [YunYouJun/utils#1]
```
home/ssx/discord-qq-bridge-2.0.4/node_modules/@yunyoujun/logger/dist/logger.js:16
    options;
           ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ssx/discord-qq-bridge-2.0.4/node_modules/@yunyoujun/logger/dist/index.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by YunYouJun** [comment]
请提供可复现仓库。

**Comment by purofle** [comment]
https://github.com/rabbitkiller-dev/discord-qq-bridge


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 晚上11:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YunYouJun/utils] 无法正常使用？ (#1)




 
请提供可复现仓库。
 
&mdash;

**Comment by YunYouJun** [comment]
复现步骤是？具体是在什么情况下会抛出异常。

**Comment by purofle** [comment]
直接启动(npm&nbsp;run&nbsp;start:dev)就会抛出异常


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 晚上11:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YunYouJun/utils] 无法正常使用？ (#1)




 
复现步骤是？具体是在什么情况下会抛出异常。
 
&mdash;

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/131370063-23b1888a-1f56-4834-a029-acfe680eecc3.png)
未复现其他报错。

**Comment by YunYouJun** [comment]
🤣 这是解决了？

**Comment by purofle** [comment]
已经解决了，换了node14


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月31日(周二) 凌晨0:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [YunYouJun/utils] 无法正常使用？ (#1)




 
藍 这是解决了？
 
&mdash;
